import MainLayout from "@/components/layouts/MainLayout";
import { Metadata } from "next";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function MainRootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
 
   return <MainLayout>{children}</MainLayout>;
}
