import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto as RobotoFont } from "next/font/google";
import "./globals.css";
import { fetchApi } from "@/lib/fetchApi";
import { getAccountApi } from "@/api/userApi";
// import MainLayout from "@/components/layouts/MainLayout";
import { AuthContextProvider } from "@/context/AuthProvider";
import { cookies } from "next/headers";
import { ProductContextProvider } from "@/context/ProductContext";

//import { getCookie } from "cookies-next/server";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
   display: "swap",
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
   display: "swap",
});

const roboto = RobotoFont({
   variable: "--font-roboto",
   subsets: ["latin"],
   display: "swap",
});

// export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
// };

export const metadata: Metadata = {
   title: "FARM-BASKET",
   description:
      "Онлайн-магазин FARM-BASKET — это удобная платформа для покупки натуральных и экологически чистых продуктов напрямую от фермеров. Ассортимент включает свежие овощи, фрукты, мясо, молочные продукты, яйца, мёд, зелень и другие товары, выращенные без использования химических добавок. Магазин предлагает быструю доставку, прозрачность происхождения каждого продукта и поддержку местных производителей. Это идеальное решение для тех, кто ценит качество, свежесть и заботу о здоровье!",

   keywords: [
      "фермерские продукты",
      "натуральные продукты",
      "свежие овощи",
      "органическая еда",
      "молочные продукты",
      "фермерское мясо",
      "домашние яйца",
      "доставка продуктов",
      "интернет магазин продуктов",
      "эко продукты",
      "здоровое питание",
   ],

   // icons: {
   //    icon: "/favicon-1.ico",
   //    apple: "/apple-touch-icon.png",
   //    other: [
   //      {
   //        rel: "mask-icon",
   //        url: "/safari-pinned-tab.svg",
   //        color: "#91bc46",
   //      },
   //    ],
   //  },

   icons: {
      icon: [
         { url: "/icons/favicon-1.ico", sizes: "128x128", type: "image/x-icon" },
      ],
      apple: [
         { url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
      ],
      other: [
         {
            rel: "mask-icon",
            url: "/icons/safari-pinned-tab.svg",
            color: "#91bc46",
         },
      ],
   },


   authors: [{ name: "FARM-BASKET", url: "https://farmbasket.by" }],
   creator: "FARM-BASKET",
   publisher: "FARM-BASKET",

   openGraph: {
      type: "website",
      locale: "ru_RU",
      url: "https://farmbasket.by",
      siteName: "FARM-BASKET",
      title: "FARM-BASKET - Натуральные фермерские продукты с доставкой",
      description:
         "Свежие овощи, фрукты, молочные продукты, мясо прямо от фермеров. Доставка по Москве. Гарантия качества.",
      images: [
         {
            url: "/SeoLogo.png",
            width: 1200,
            height: 630,
            alt: "FARM-BASKET - Фермерские продукты",
            type: "image/png",
         },
      ],
   },

   // Twitter карточки
   twitter: {
      card: "summary_large_image",
      title: "FARM-BASKET - Фермерские продукты с доставкой",
      description: "Натуральные продукты прямо от производителей",
      images: ["https://farmbasket.by/SeoLogo.png"],
      creator: "@farmbasket_by",
      site: "@farmbasket_by",
   },

   // Robots настройки
   robots: {
      index: true,
      follow: true,
      nocache: false,
      googleBot: {
         index: true,
         follow: true,
         noimageindex: false,
         "max-video-preview": -1,
         "max-image-preview": "large",
         "max-snippet": -1,
      },
   },

   

   // // Манифест
   // manifest: "/manifest.json",

   // Альтернативные ссылки
   alternates: {
      canonical: "https://farmbasket.by",
      languages: {
         "ru-RU": "https://farmbasket.by",
         "en-US": "https://farmbasket.by/en",
      },
   },

   // Категория контента
   category: "food",

   // Дополнительные метатеги
   other: {
      // Для Google
      "google-site-verification": "your-google-verification-code",

      // Для Yandex
      "yandex-verification": "your-yandex-verification-code",

      // Тематика сайта
      "theme-color": "#91bc46",
      "color-scheme": "light",

      // Для iOS Safari
      "apple-mobile-web-app-capable": "yes",
      "apple-mobile-web-app-status-bar-style": "default",
      "apple-mobile-web-app-title": "FARM-BASKET",

      // Для Microsoft
      "msapplication-TileColor": "#91bc46",
      "msapplication-config": "/browserconfig.xml",

      // Дополнительная информация
      "format-detection": "telephone=no",
      "mobile-web-app-capable": "yes",

      // // Geo теги (если есть физический магазин)
      // "geo.region": "BY-GR",
      // "geo.placename": "Москва",
      // "geo.position": "55.755814;37.617635", // координаты Москвы

      // Рейтинг контента
      rating: "general",

      // Права
      copyright: "FARM-BASKET",

      // Для поисковиков
      "revisit-after": "7 days",
   },

   // Метаданные приложения
   applicationName: "FARM-BASKET",

   // Referrer policy
   referrer: "origin-when-cross-origin",

   // Viewport (обычно в HTML, но можно и здесь)
   viewport: {
      width: "device-width",
      initialScale: 1,
      maximumScale: 1,
      userScalable: false,
      interactiveWidget: "resizes-content",
   },
};

export default async function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   const token = (await cookies()).get("token")?.value;
   let userType = "guest";

   if (token) {
      try {
         const res = await fetchApi(getAccountApi(token));
         if (res.success) {
            userType = res.data.account_type.toString();
         } else {
            userType = "guest";
         }
      } catch (e) {
         console.error("Ошибка получения аккаунта:", e);
      }
   }

   return (
      <html lang="ru">
         <body
            className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
         >
            <AuthContextProvider initialUserType={userType}>
               <ProductContextProvider>{children}</ProductContextProvider>
            </AuthContextProvider>
         </body>
      </html>
   );
}
